### ISSUE TITLE
Add multiple remote support

### ISSUE THREAD

**Issue by cleversprocket** [msiemens/PyGitUp#10]
Feature Request :) Supporting multiple remotes would be very handy.

**Comment by alecswan** [comment]
I am using git-up v2.3.0 and observing the it only pulls changes from the first remote listed by "git remote -v". 

I have two remotes: one - in github, one in gitlab, both are registered for (fetch) and (push) and "git remote -v" lists them in this order when I am on the "main" branch: 

1. cicd github (fetch)
2. cicd github (push)
3. origin gitlab (fetch) 
4. origin gitlab (push)

** Note that "origin" remote is listed last. 

On machine A, I pushed a change to origin/main (gitlab). On machine B, "git log origin/main" shows that change. However, when I run "git up" on machine B, it does NOT pull those changes.

I tried setting git-up.fetch.all=true in git config, but that didn't help.

Thoughts?

**Comment by alecswan** [comment]
Answering my own question after some troubleshooting.

I used `git branch -vv` to detremine that my local "main" branch was tracking cicd/main remote branch and that's why all changes were being pulled from cicd remote by default.

Running `git branch -u origin/main` made my local main branch track origin/main remote branch which made `git up` pull changes from origin/main as desired.

I wish it was possible to have `git up` pull changes in each branch from multiple remotes.
