### ISSUE TITLE
git up --help doesn't behave as expected

### ISSUE THREAD

**Issue by d33tah** [msiemens/PyGitUp#36]
```
$ git up --help
No manual entry for git-up
```

**Comment by msiemens** [comment]
You can to use `git up -h` instead. `--help` is intercepted by git itself and looks up a man page which we don't have.

**Comment by d33tah** [comment]
Perhaps creating a man page would be a solution?

**Comment by msiemens** [comment]
I've already considered that but I've found several obstacles to creating a man page:

1. Where to install it on Windows?
2. Should we try to create a man page dynamically from the readme? Otherwise we'd have to maintain it separately creating duplicate work.
3. On Linux/Mac you'd need root access to install the man page meaning it wouldn't work for users without root access. Also we'd need a solid install mechanism which in itself is challenging.

For comparison, [ansible](https://github.com/ansible/ansible) does have man page, but they are only bundled when installed with the OS package manager ([source](https://github.com/ansible/ansible/issues/7790)).

**Comment by d33tah** [comment]
It looks like it's more difficult than I expected. I guess you would need an .rst to manpage converter, not install it anywhere on Windows and on Linux, only add it for root in the easiest approach. The question is whether it's worth it.

**Comment by msiemens** [comment]
Closing this as `git up -h` works and creating a working solution for `git up --help` would be very complicated.
