### ISSUE TITLE
Error on deleted branches

### ISSUE THREAD

**Issue by thomwiggers** [msiemens/PyGitUp#54]
I'm getting errors on remotely deleted branches, they don't get removed as expected:

Example:

```
repo $ git up                            
Fetching origin
23-1-signup-form         error: remote branch doesn't exist
exportimprovements       error: remote branch doesn't exist
feature/docker           up to date
```

I'm on git version 2.10.1 on Arch Linux.

**Comment by msiemens** [comment]
Hey, by default PyGitUp doesn't delete missing remote tracking branches. Do you run it with `git-up.fetch.prune` enabled (see https://github.com/msiemens/PyGitUp#configuration)?

**Comment by thomwiggers** [comment]
I thought that was the default, and even after enabling it I get the same errors.

**Comment by SeerUK** [comment]
I'm also having this issue, using 2.11.0, on OSX 10.11.6, PyGitUp 1.4.5. I've explicitly set the option to true, and also thought it was the default, here's the excerpt from my global git configuration file:

```
[git-up "fetch"]
    prune = true
```

**Comment by AndreasBoehm** [comment]
Any fix for this? Its really annoying!

git version 2.12.2
GitUp version is: v1.4.5
macOS 10.12.4

**Comment by msiemens** [comment]
As I understand now the issue seems to be that `git fetch --prune` only removes local references to remote branches, not local branches based on those local references (see http://stackoverflow.com/a/20107184/997063). Removing local branches where the remote branch has been deleted would be a new feature for PyGitUp.

Now it isn't clear to me how exactly this should be implemented. How exactly should local branches be deleted (`git branch -d` vs. `git branch -D`)? What should happen if there's only one branch checked out and the remote branch is deleted?

**Comment by msiemens** [comment]
Closing this as this issue is now more than three years old without a respose. If anyone still has this issue, feel free to comment and I'll reopen it.
