### ISSUE TITLE
GIT_DIR is not respected

### ISSUE THREAD

**Issue by kwbr** [msiemens/PyGitUp#58]
The way git-up tries to get the path to the repository is not working when the GIT_WORK_TREE and GIT_DIR are different.

```get_git_dir()``` tries to get the repository with

```return execute(['git', 'rev-parse', '--show-toplevel'])```

As far as I understand ```--git-dir``` should be used.

http://stackoverflow.com/a/21085415

**Comment by astitcher** [comment]
I'm assuming this issue is raised because git up doesn't work correctly if you are working in a work tree created by `git worktree ...`.

In this case I'm not sure if the correct way to get the repository is `--git-dir` or `--git-common-dir`.

From a little experimentation `--git-dir` gives a location deep inside the repository whereas `--git-common-dir` gives the actual repository root.

**Comment by kwbr** [comment]
You are correct. I use vcsh (https://github.com/RichiH/vcsh) which separates the worktree from the git-dir. After reading the documentation --git-common-dir seem to be the correct way

**Comment by msiemens** [comment]
Thanks for the bug report and the details everyone! I've implemented a fix, but it seems like the git version on Travis doesn't support git's worktree. @kwbr Could you install the latest dev version (should work using `pip install https://github.com/msiemens/PyGitUp`) and report if it's actually fixed?

**Comment by kwbr** [comment]
Seems to work now. :+1: 

Installed it with ```pip install git+https://github.com/msiemens/PyGitUp```.

**Comment by msiemens** [comment]
Awesome! Version 1.4.4 has been released now :)
